### ISSUE TITLE
Overwatch Top Heroes

### ISSUE THREAD

**Issue by KannaDev** [KannaDev/Kanna-Bot#16]
Need to include Top Heroes/Champions in overwatch stats.

`!ow <username#battleTag>` - Should also display top heroes next to profile stats

**Comment by imaginebeingme** [comment]
![overwatch](https://user-images.githubusercontent.com/41272291/43813279-58159d76-9b08-11e8-9c0e-59bfabe78897.png)


I created this one, image at the bottom is most used / played Champion. *Unsure* if you can do multiple Heroes.

**Comment by KannaDev** [comment]
Thank you for the example! 
What API are you using?

**Comment by imaginebeingme** [comment]
Regular old Discord.js, I've only just started using superagent seeing as though what you can do with it (Saw your work) 

I can shoot over the coding if you want, you can change it up to your liking and such if you feel the need.
@

**Comment by imaginebeingme** [comment]
@KannaDev  makes sense, Probably the more logical way of doing it, instead of clunking up the feed with a long Rich.embed. Best of luck! :)

**Comment by KannaDev** [comment]
@imaginebeingme Thank you! Good luck to you too on your cuck bot
